# 1. Tratamento de dados

Os passos a seguir tem por objetivo tornar os dados adequados às etapas seguintes.

In [13]:
# importa bibliotecas necessárias para tratamento de dados
import pandas as pd

In [14]:
# instancia os dados em um dataframe
df = pd.read_csv('data/planilha_usinagem.csv', sep=';')

In [15]:
# exibe informações sobre as colunas
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Data                                       185 non-null    str
 1   Fabricante do Hob                          185 non-null    str
 2   Revestimento                               185 non-null    str
 3   Fabricante                                 185 non-null    str
 4   Avanço mm/rev.                             185 non-null    str
 5   Rotação RPM                                185 non-null    int64
 6   Vc m/min                                   185 non-null    float64
 7   Shifting mm                                185 non-null    float64
 8   Sub-Shift mm                               185 non-null    float64
 9   CT (S)                                     185 non-null    str
 10  Quantidade de pçs por afiação Target 1950  175 non-null    float64
 11  dureza sup                                 173 non-null    float64
 12  dureza nuc                                 174 non-null    float64
dtypes: float64(6), int64(1), str(6)
memory usage: 18.9 KB

Este material tem por objetivo montar uma lógica de apredizado de máquina e usa uma base dedos preenchida manualmente e obtida, e não criada, por este desenvolvedor. Por este motivo, optou-se pelo descarte dos dados faltantes. Em trabalhos futuros objetiva-se criar mecanismos de obtenção de dados mais eficazes a fim de garantir a maior robustez dos dados.

In [16]:
# exclue todas as linhas com itens faltantes
df_limpo = df.dropna()

In [17]:
# exibe informações sobre as colunas
df_limpo.info()

<class 'pandas.DataFrame'>
Index: 153 entries, 0 to 184
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Data                                       153 non-null    str
 1   Fabricante do Hob                          153 non-null    str
 2   Revestimento                               153 non-null    str
 3   Fabricante                                 153 non-null    str
 4   Avanço mm/rev.                             153 non-null    str
 5   Rotação RPM                                153 non-null    int64
 6   Vc m/min                                   153 non-null    float64
 7   Shifting mm                                153 non-null    float64
 8   Sub-Shift mm                               153 non-null    float64
 9   CT (S)                                     153 non-null    str
 10  Quantidade de pçs por afiação Target 1950  153 non-null    float64
 11  dureza sup                                 153 non-null    float64
 12  dureza nuc                                 153 non-null    float64
dtypes: float64(6), int64(1), str(6)
memory usage: 16.7 KB

In [18]:
# exibe os valores únicos de cada coluna

for col in df_limpo.columns: # loop para iterar sobre todas as colunas
    print(f"Valores únicos de '{col}'") # imprime o nome da coluna
    print(df_limpo[col].unique()) # imprime os valores únicos da coluna
    print('----------------------------------------------------------------------') # imprime um separador entre cada iteração

Valores únicos de 'Data'
<StringArray>
['2025-01-02 00:00:00', '2025-01-05 00:00:00', '2025-01-14 00:00:00',
 '2025-01-15 00:00:00', '2025-01-21 00:00:00', '2025-01-28 00:00:00',
 '2025-02-02 00:00:00', '2025-02-04 00:00:00', '2025-02-05 00:00:00',
 '2025-02-10 00:00:00',
 ...
 '2026-04-30 00:00:00', '2026-05-04 00:00:00', '2026-05-05 00:00:00',
 '2026-05-08 00:00:00', '2026-05-12 00:00:00', '2026-05-14 00:00:00',
 '2026-05-18 00:00:00', '2026-05-24 00:00:00', '2026-05-25 00:00:00',
 '2026-05-26 00:00:00']
Length: 126, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Fabricante do Hob'
<StringArray>
['SU', 'S.U.', 'Nidec']
Length: 3, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Revestimento'
<StringArray>
['Alcrona Pro', 'Alcrona Evo']
Length: 2, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Fabricante'
<StringArray>
['Balzers']
Length: 1, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Avanço mm/rev.'
<StringArray>
['1.75', '1.4', '2.0', '1.5', '\']
Length: 5, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Rotação RPM'
[350 390 320 510]
----------------------------------------------------------------------
Valores únicos de 'Vc m/min'
[ 98.96  110.27   90.478 144.199]
----------------------------------------------------------------------
Valores únicos de 'Shifting mm'
[10.  11.4]
----------------------------------------------------------------------
Valores únicos de 'Sub-Shift mm'
[0.666667 0.76    ]
----------------------------------------------------------------------
Valores únicos de 'CT (S)'
<StringArray>
['42,9', '38,5', '46,9', '29,4']
Length: 4, dtype: str
----------------------------------------------------------------------
Valores únicos de 'Quantidade de pçs por afiação Target 1950'
[2620. 2458. 2718. 2496. 1872. 2850. 2063. 3003. 3004. 2055. 2333. 2747.
 2604. 2405. 2228. 1692. 2239. 2702. 2808. 2127. 2493. 2116. 2385. 2734.
 2626. 2478. 1738. 2559. 2878. 2328. 2709. 2142. 2084. 2545. 3263. 2994.
 2207. 2523. 2434. 2482. 2476. 2031. 2568. 2757. 2321. 2470. 2249. 2952.
 2353. 2893. 2014. 2539. 1908. 2696. 1930. 2646. 2873. 2663. 2050. 1680.
 2027. 2745. 2903. 2240. 2794. 2692. 1981. 2473. 2179. 2130. 2489. 2435.
 2307. 2364. 2264. 2640. 2208. 2855. 2255. 2257. 2754. 2641. 1779. 2461.
 2791. 2575. 2015. 2503. 2875. 2677. 2858. 2813. 2218. 1888. 2345. 2222.
 2535. 2369. 3020. 1794. 2581. 2408. 3069. 1938. 2237. 2779. 1945. 2378.
 2317. 2887. 2495. 2375. 2340. 2404. 2899. 2731. 2341. 2012. 2861. 2849.
 2450. 3089. 2367. 2159. 2252. 2504. 2679. 3014. 2413. 1983. 2291. 2412.
 2343. 2627. 2184. 2818. 2666. 2585. 1902. 2414. 2336. 2453. 3125. 2683.]
----------------------------------------------------------------------
Valores únicos de 'dureza sup'
[ 94.3  90.4  98.6  93.9  92.   95.4  98.1  96.2  93.8  96.7  96.4  97.4
  95.   97.3  99.1  98.4  94.8  97.   93.3  94.   99.8  95.1  94.9  94.6
  99.5  98.5  90.2  96.5 102.6  96.1 100.5  97.5  97.1  92.6  96.3  95.8
  98.  102.3  94.5  98.7  97.6  99.2  92.2  95.3  93.2  95.6  96.   92.7
  91.4  93.5  97.7  89.4  92.9  97.2  94.1  94.2  95.7  93.4  93.6  96.6
 100.1  94.4  93.7  91.8 100.4  99.3  91.6  97.9  90.6  95.9  95.2 101.4
  92.8  91.9 101.   97.8  99.9  90.1  92.4 101.2]
----------------------------------------------------------------------
Valores únicos de 'dureza nuc'
[96.5 93.1 94.6 94.4 93.2 93.9 90.1 95.2 95.3 91.3 96.3 89.6 96.9 90.7
 93.4 96.7 94.3 95.5 97.2 92.9 95.6 90.2 96.  95.1 93.5 96.8 93.8 92.8
 96.2 90.5 95.  89.2 92.4 96.6 90.6 95.8 97.1 87.8 94.8 89.8 91.8 92.
 91.4 91.  95.7 93.6 91.9 99.8 92.3 98.1 94.2 92.7 95.4 91.1 94.9 92.2
 99.9 90.9 85.3 97.  97.3 91.2 89.9 96.1 97.8 94.  90.3 94.1 95.9 97.7
 94.5 93.  90.4 89.5 96.4 93.7 88.9 98.2]
----------------------------------------------------------------------

In [19]:
# remove sujeira da coluna 'Avanço mm/rev.'

df_limpo = df_limpo[df_limpo['Avanço mm/rev.'] != '\\'] # remove a linha com '\' da colunas 'Avanço mm/rev.'
print("Valores únicos da coluna 'Avanço mm/rev.'") # uma pequena descrição
print(df_limpo['Avanço mm/rev.'].unique()) # imprime os valores únicos da coluna

Valores únicos da coluna 'Avanço mm/rev.'
<StringArray>
['1.75', '1.4', '2.0', '1.5']
Length: 4, dtype: str

In [20]:
# corrige os valores da coluna 'CT (S)'

df_limpo['CT (S)'] = df_limpo['CT (S)'].astype(str).str.replace(',', '.') # substitue os algorítimos decimais ',' por '.' na coluna 'CT(S)'
print("Valores únicos da coluna 'CT (S)'") # uma pequena descrição
print(df_limpo['CT (S)'].unique()) # imprime os valores únicos da coluna

Valores únicos da coluna 'CT (S)'
<StringArray>
['42.9', '38.5', '46.9', '29.4']
Length: 4, dtype: str

In [21]:
df_limpo['Fabricante do Hob'].value_counts()

Fabricante do Hob
SU       124
S.U.      15
Nidec     13
Name: count, dtype: int64

Das 104 entradas remanecentes em df_limpo, apenas 1 refere-se a 'Fabricante do Hob' Nidec. Por este motivo, será considerada como coluna de valor único. Além disso, para este estudo, também será descartada a coluna data visto que o modelo não usará séries temporais

In [22]:
# elimina as colunas de valor único
df_limpo = df_limpo.drop(columns=['Data', 'Fabricante', 'Fabricante do Hob'])

In [23]:
# descarta possíveis linhas duplicadasd
df_limpo = df_limpo.drop_duplicates()

In [24]:
# converte as colunas faltantes para os tipos finais

colunas_converter_float = ['Avanço mm/rev.', 'CT (S)'] # define as colunas a serem corrigidas

for coluna in colunas_converter_float: # loop para iterar sobre as colunas a sere corrigidas
    df_corrigido = df_limpo # copia df_limpo para um novo dataframe
    df_corrigido[coluna] = df_corrigido[coluna].astype(float) # converte as colunas em colunas_converter_float para float

df_corrigido['Quantidade de pçs por afiação Target 1950'] = df_corrigido['Quantidade de pçs por afiação Target 1950'].astype(int) # converte a 'Quantidade de pçs por afiação Target 1950' para int64

df_corrigido.info() # exibe informações sobre as colunas

<class 'pandas.DataFrame'>
Index: 152 entries, 0 to 184
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Revestimento                               152 non-null    str
 1   Avanço mm/rev.                             152 non-null    float64
 2   Rotação RPM                                152 non-null    int64
 3   Vc m/min                                   152 non-null    float64
 4   Shifting mm                                152 non-null    float64
 5   Sub-Shift mm                               152 non-null    float64
 6   CT (S)                                     152 non-null    float64
 7   Quantidade de pçs por afiação Target 1950  152 non-null    int64
 8   dureza sup                                 152 non-null    float64
 9   dureza nuc                                 152 non-null    float64
dtypes: float64(7), int64(2), str(1)
memory usage: 13.1 KB

In [25]:
df_corrigido

,Revestimento,Avanço mm/rev.,Rotação RPM,Vc m/min,Shifting mm,Sub-Shift mm,CT (S),Quantidade de pçs por afiação Target 1950,dureza sup,dureza nuc
0,Alcrona Pro,1.75,350,98.960,10.0,0.666667,42.9,2620,94.3,96.5
1,Alcrona Evo,1.40,390,110.270,11.4,0.760000,38.5,2458,90.4,93.1
2,Alcrona Pro,1.75,320,90.478,11.4,0.760000,46.9,2718,98.6,94.6
3,Alcrona Evo,1.40,320,90.478,10.0,0.666667,46.9,2496,93.9,94.4
4,Alcrona Evo,2.00,510,144.199,10.0,0.666667,29.4,1872,92.0,93.2
...,...,...,...,...,...,...,...,...,...,...
177,Alcrona Evo,1.75,350,98.960,10.0,0.666667,42.9,2414,95.2,93.7
180,Alcrona Evo,1.40,510,144.199,11.4,0.760000,29.4,2336,97.5,98.2
181,Alcrona Evo,1.50,320,90.478,11.4,0.760000,46.9,2453,92.2,96.2
183,Alcrona Pro,1.40,320,90.478,10.0,0.666667,46.9,3125,94.4,92.2
184,Alcrona Pro,1.50,510,144.199,11.4,0.760000,29.4,2683,91.8,92.3

# 2. Análise Exploratória dos Dados (EDA)

In [26]:
# importa bibliotecas necessárias para a EDA
import plotly.express as px

In [27]:
# cria um histograma da coluna 'Quantidade de pçs por afiação Target 1950'

fig = px.histogram( # cria uma figura para o gráfico
    df_corrigido, # define o df a ser usado
    x='Quantidade de pçs por afiação Target 1950', # define os valores de X
    nbins=10, # sugestioná o número de barras do hostograma usando o método da raiz quadrada (k = n^(1/2) ==> nbins = 104 linhas^(1/2))
    title='Distribuição da Quantidade de Peças por Afiação', # define um título para o gráfico
    labels={'Quantidade de pçs por afiação Target 1950': 'Quantidade de Peças'}, # múda o título do eixo X de 'Quantidade de pçs por afiação Target 1950' para 'Quantidade de Peças'
    color_discrete_sequence=['#1f77b4'] # define a cor padrão como azul
)

fig.update_layout(yaxis_title='Frequência') # muda o título do eixo Y de 'count' para 'Frequência'

fig.show() # exibe a figura

Através do histograma da distribuição da quantidade de peças por afiação é possível observar um comportamento normal em quase todas as faixas com excessão da faixa de 3500 a 3999 peças por afiação que apresenta uma única insidência. O que pode indicar um erro de durante a aquisição desse dado (erro de digitação, por exemplo) ou um evento anormalmente favorável à durabilidade da ferramenta.

In [28]:
# cria um gráfico de boxplot da relação entre 'Revestimento' e 'Quantidade de pçs por afiação Target 1950'

fig_box = px.box( # cria uma figura para o boxplot
    df_corrigido, # define o df a ser usado
    x='Revestimento', # define os valores de X
    y='Quantidade de pçs por afiação Target 1950', # define os valores de Y 
    color='Revestimento', # separa os dados conforme 'Revestimento'
    title='Variação da Vida Útil por Revestimento', # define um título para o gráfico
    labels={'Quantidade de pçs por afiação Target 1950': 'Peças Produzidas'} #  # múda o título do eixo X de 'Quantidade de pçs por afiação Target 1950' para 'Quantidade de Peças'
)

fig_box.show() # exibe a figura

Apesar de ser mais notável no Revestimento 'Alcrona Evo', ambos os revestimentosapresentam apresentam uma variação muito maior na vida útil do que o esperado. É necessessário investigar o motivo desta variação.

In [29]:
# cria um heatmap das variáveis numéricas de df_corrigido

df_numerico = df_corrigido.select_dtypes(include=['float64', 'int64']) # cria df_numerico com apneas as colunas numéricas de df_corrigido

matriz_correlacao = df_numerico.corr(method='spearman') # cria uma matriz de correlação das colunas de df_numerico

fig_corr = px.imshow( # cria uma figura para o heatmap
    matriz_correlacao, # define a matriz a ser usado
    text_auto=".2f", # mostra os valores com 2 casas decimais
    aspect="auto", # define a proporção do heatmap como automática forçañdo-o a preencher a altura e largura da figura
    color_continuous_scale='RdBu_r', # define a escala de cores como Azul para positivo e Vermelho para negativo
    title='Matriz de Correlação entre Parâmetros de Usinagem' # define o título do gráfico
)

fig_corr.show() # exibe a figura

Não foi possível identificar nenhuma correlação linear direta entre as features e a variável alvo 'Quantidade de pçs por afiação Target 1950'. No entanto algumas features apresentaram relações fortíssimas. Relações desse tipo indicam redundancia nas medições e pode ser descartadas para melhorar a eficiência do futuro modelo preditivo. Por este motivo serão descartadas as seguintes colunas:

* 'Vc m/min' : Correlação de 99% com 'Rotação RPM'
* 'CT (s)' : Correlação de 99% com 'Rotação RPM'
* 'Sub-shift mm' :  Correlação de 100% com 'Shifting mm'

In [30]:
df_corrigido

,Revestimento,Avanço mm/rev.,Rotação RPM,Vc m/min,Shifting mm,Sub-Shift mm,CT (S),Quantidade de pçs por afiação Target 1950,dureza sup,dureza nuc
0,Alcrona Pro,1.75,350,98.960,10.0,0.666667,42.9,2620,94.3,96.5
1,Alcrona Evo,1.40,390,110.270,11.4,0.760000,38.5,2458,90.4,93.1
2,Alcrona Pro,1.75,320,90.478,11.4,0.760000,46.9,2718,98.6,94.6
3,Alcrona Evo,1.40,320,90.478,10.0,0.666667,46.9,2496,93.9,94.4
4,Alcrona Evo,2.00,510,144.199,10.0,0.666667,29.4,1872,92.0,93.2
...,...,...,...,...,...,...,...,...,...,...
177,Alcrona Evo,1.75,350,98.960,10.0,0.666667,42.9,2414,95.2,93.7
180,Alcrona Evo,1.40,510,144.199,11.4,0.760000,29.4,2336,97.5,98.2
181,Alcrona Evo,1.50,320,90.478,11.4,0.760000,46.9,2453,92.2,96.2
183,Alcrona Pro,1.40,320,90.478,10.0,0.666667,46.9,3125,94.4,92.2
184,Alcrona Pro,1.50,510,144.199,11.4,0.760000,29.4,2683,91.8,92.3

In [31]:
# seleciona as features que serão usadas no modelo

df_selecionado = df_corrigido # copia o df_corrigido em df_selecionado
df_selecionado = df_selecionado.drop(columns=['Vc m/min', 'CT (S)', 'Sub-Shift mm']) # descarta as colunas 'Vc m/min', 'CT (S)' e 'Sub-Shift mm'
df_selecionado.head() # exibe df_selecionado

,Revestimento,Avanço mm/rev.,Rotação RPM,Shifting mm,Quantidade de pçs por afiação Target 1950,dureza sup,dureza nuc
0,Alcrona Pro,1.75,350,10.0,2620,94.3,96.5
1,Alcrona Evo,1.40,390,11.4,2458,90.4,93.1
2,Alcrona Pro,1.75,320,11.4,2718,98.6,94.6
3,Alcrona Evo,1.40,320,10.0,2496,93.9,94.4
4,Alcrona Evo,2.00,510,10.0,1872,92.0,93.2

# 3. Feature Engineering (Encoding e divisão target-features)

In [32]:
# One Hot Encoding na variável categórica 'Revestimento'
df_modelo = pd.get_dummies(df_selecionado, columns=['Revestimento'], drop_first=True, dtype=int).reset_index(drop=True)

In [33]:
# divisão target-features de df_modelo

X = df_modelo.drop(columns=['Quantidade de pçs por afiação Target 1950']) # separa todas as features em X
y = df_modelo['Quantidade de pçs por afiação Target 1950'] # separa o alvo em y

# 4. Treinamento e avaliação

In [34]:
# importa bibliotecas necessárias para treinamento e avaliação
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [35]:
# divide X e y em treino e teste na proporção 80/20
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
# instancia o modelo
modelo_random_forest = RandomForestRegressor(n_estimators=100, random_state=42) # n_estimators=100 significa que o modelo criará 100 "árvores de decisão" diferentes

In [37]:
modelo_random_forest.fit(X_treino, y_treino)

RandomForestRegressor(random_state=42)

In [38]:
# realiza a previsão sobre o X_teste
previsao = modelo_random_forest.predict(X_teste)

In [39]:
# calcular as métricas de desempenho

mae = mean_absolute_error(y_teste, previsao) # calcula o Mean Absolute Error
rmse = np.sqrt(mean_squared_error(y_teste, previsao)) # calcula Root Mean Square Error
r2 = r2_score(y_teste, previsao) # calcula R2

print("\n--- Desempenho do Modelo ---")
print(f"MAE (Erro Médio Absoluto): {mae:.2f} peças") # representa, em média, por quantas peças o modelo está errando
print(f"RMSE (Erro Quadrático Médio): {rmse:.2f} peças") # similar ao MAE, mas pune com maior rigor os erros mais discrepantes por se tratar de um cálculo quadrático
print(f"R² Score: {r2:.2f}") # é a previsibilidade do seu modelo. Quanto de y_teste é explicado pelos valores de X_teste

--- Desempenho do Modelo ---
MAE (Erro Médio Absoluto): 157.88 peças
RMSE (Erro Quadrático Médio): 209.49 peças
R² Score: 0.65